In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import pandas as pd

In [2]:
articles = [
    "OpenAI releases new GPT model for developers",
    "India wins cricket series against Australia",
    "AI startup raises $50 million in funding",
    "Global stock markets fall after inflation fears",
    "New machine learning breakthrough announced",
    "Celebrity buys luxury mansion in Los Angeles",
    "Tech companies invest heavily in artificial intelligence",
]

user_interest = (
    "artificial intelligence machine learning "
    "technology startups world news"
)

In [9]:
all_text = [user_interest] + articles

vectorizer = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = vectorizer.fit_transform(all_text)

print(tfidf_matrix.shape)

(8, 42)

In [10]:
user_vector = tfidf_matrix[0:1]

article_vectors = tfidf_matrix[1:]

scores = cosine_similarity(
    user_vector,
    article_vectors,
)[0]

scores

array([0.        , 0.16833333, 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [11]:
results = pd.DataFrame({
    "Article": articles,
    "ML Score": scores,
})

results = results.sort_values(
    by="ML Score",
    ascending=False,
)

results

                                             Article  ML Score
1        India wins cricket series against Australia  0.168333
0       OpenAI releases new GPT model for developers  0.000000
2           AI startup raises $50 million in funding  0.000000
3    Global stock markets fall after inflation fears  0.000000
4        New machine learning breakthrough announced  0.000000
5       Celebrity buys luxury mansion in Los Angeles  0.000000
6  Tech companies invest heavily in artificial in...  0.000000

In [12]:
results["ML Score"] = results["ML Score"].round(3)

results

                                             Article  ML Score
1        India wins cricket series against Australia     0.168
0       OpenAI releases new GPT model for developers     0.000
2           AI startup raises $50 million in funding     0.000
3    Global stock markets fall after inflation fears     0.000
4        New machine learning breakthrough announced     0.000
5       Celebrity buys luxury mansion in Los Angeles     0.000
6  Tech companies invest heavily in artificial in...     0.000

In [7]:
user_interest = (
    "sports football cricket athletes"
)